name: CI

on: [push, pull_request]

permissions:
  contents: read

jobs:
  CI:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php:
          - '8.0'
          - '8.1'
          - '8.2'
          - '8.3'
    steps:
      - uses: shivammathur/setup-php@2.28.0
        with:
          php-version: ${{ matrix.php }}
      - uses: actions/checkout@v3
      - run: composer install --no-progress --no-ansi --no-interaction --dev --prefer-dist
      - run: php test/test.php
